name: Coverage and SonarCloud

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: bw-output
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build-wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v8.2.0

      - name: Install gtest
        run: wget https://gist.githubusercontent.com/Ponomarevda/d970c24de8deab5d6ccfee8f5f719bcc/raw/install_gtest_ubuntu.sh && chmod +x install_gtest_ubuntu.sh && ./install_gtest_ubuntu.sh

      - name: Run build-wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make coverage

      - name: Run SonarQube Scan
        if: github.event.repository.fork == false
        uses: SonarSource/sonarqube-scan-action@v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define "sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
